'\" t
.\"     Title: chpasswd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 07/27/2018
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.5
.\"  Language: Russian
.\"
.TH "chpasswd" "8" "07/27/2018" "shadow\-utils 4\&.5" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
chpasswd \- обновляет пароли в пакетном режиме
.SH "СИНТАКСИС"
.HP \w'\fBchpasswd\fR\ 'u
\fBchpasswd\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchpasswd\fR
читает список пар \(Foпользователь пароль\(Fc из стандартного входного потока и обновляет информацию о существующих пользователях\&. Каждая строка имеет вид:
.PP
\fIимя_пользователя\fR:\fIпароль\fR
.PP
По умолчанию, передаваемый пароль должен быть в виде обычного текста и шифруется командой
\fBchpasswd\fR\&. Также, если есть срок действия пароля, то он будет обновлён\&.
.PP
По умолчанию пароли шифруются PAM, но (даже если это не рекомендуется) вы можете выбрать другой метод шифрования с помощью параметра
\fB\-e\fR,
\fB\-m\fR
или
\fB\-c\fR\&.
.PP
Except when PAM is used to encrypt the passwords,
\fBchpasswd\fR
first updates all the passwords in memory, and then commits all the changes to disk if no errors occurred for any user\&.
.PP
В случае когда шифрование паролей (и обновление в системной базе данных) выполняется PAM и пароль не может быть обновлён, то
\fBchpasswd\fR
продолжает обновление паролей остальных пользователей и завершает работу с кодом ошибки\&.
.PP
Данная команда предназначена для работы в крупных системных средах, где за один раз заводится несколько учётных записей\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchpasswd\fR:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR\ \&\fIМЕТОД\fR
.RS 4
Использовать указанный метод для шифрования паролей\&.
.sp
Возможные методы: DES, MD5, NONE и SHA256 или SHA512, если эти методы поддерживается libc\&.
.sp
По умолчанию, для шифрования паролей используется PAM\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 4
Передаваемые пароли заданы в шифрованном виде\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 4
Использовать алгоритм шифрования MD5 вместо DES, если пароли передаются не шифрованными\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR\ \&\fIРАУНДОВ\fR
.RS 4
Использовать указанное количество раундов шифрования паролей\&.
.sp
Значение 0 означает, что система выберет количество раундов по умолчанию для выбранного метода шифрования (5000)\&.
.sp
Минимальное значение равно 1000, а максимальное значение равно 999,999,999\&.
.sp
Вы можете использовать этот параметр только при методе шифрования SHA256 или SHA512\&.
.sp
По умолчанию, количество раундов определяется переменными
\fBSHA_CRYPT_MIN_ROUNDS\fR
и
\fBSHA_CRYPT_MAX_ROUNDS\fR
в
/etc/login\&.defs\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Не забудьте установить права или umask, чтобы не позволить чтение не шифрованных файлов другими пользователями\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (число), \fBSHA_CRYPT_MAX_ROUNDS\fR (число)
.RS 4
Если значение
\fBENCRYPT_METHOD\fR
равно
\fISHA256\fR
или
\fISHA512\fR, эта переменная определяет количество раундов SHA, используемых алгоритмом шифрования по умолчанию (если количество раундов не задано в командной строке)\&.
.sp
Увеличение количества раундов повышает сложность подбора пароля простым перебором\&. Но заметим, что при этом для аутентификации пользователей требуется большее количество процессорных ресурсов\&.
.sp
Если не задана, то libc выбирает значение количества раундов по умолчанию (5000)\&.
.sp
Значения должны лежать в диапазоне 1000\-999999999\&.
.sp
Если задано какое\-то одно значение \(em
\fBSHA_CRYPT_MIN_ROUNDS\fR
или
\fBSHA_CRYPT_MAX_ROUNDS\fR
\(em то будет использовано это значение\&.
.sp
Если
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, то используется большее значение\&.
.sp
Замечание: действует только при генерации паролей к группам\&. Генерация пользовательских паролей выполняется PAM и там же настраивается\&. Рекомендуется устанавливать значение этой переменной согласно настройкам PAM\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.PP
/etc/pam\&.d/chpasswd
.RS 4
настройки PAM для
\fBchpasswd\fR
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBlogin.defs\fR(5),\fBuseradd\fR(8)\&.
